--Adding indexes for better performance:

CREATE INDEX IDX_ENROLLMENT_COURSE_FK ON SYS_Enrollment(COURSE_ID);

CREATE INDEX IDX_SYS_USER ON SYS_Instructor(USER_ID);
CREATE INDEX Idx_COURSE_USER_FK ON SYS_SESSION(SESSION_TITLE);

CREATE INDEX IDX_COURSE_USER_STATUS ON SYS_COURSE(USER_ID, STATUS);
CREATE INDEX IDX_COURSE_NAME ON SYS_COURSE(COURSE_NAME);