spring.application.name=GRADUATION

server.port=1010

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=GRADUATION
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.issuer=GRADUATION
jwt.expiration=60

# Flyway Configuration  - TEMPORARILY DISABLED when Schema Generation settings are in use
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=GRADUATION
spring.flyway.clean-disabled=true

# JPA / Hibernate

#Schema Generation Settings:
#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/generated-schema.sql


#none when Schema Generation Settings in use, validate after generating schema to check against the db
spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
