spring.application.name=E-Learning

server.port=1010

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=UPSKILLING_APP
spring.datasource.password=app123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=UPSKILLING_APP


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


#jwt
jwt.secret=fbkgjhreugh75nglkrefh21f5weaS@#!Fbdhsfjgdsg1564gSDCASD
jwt.issuer=ELearningApplication
#60 foe learning project only
jwt.expiration=60
