-- ============================================================
--  Hibernate Created it:
-- Initial Oracle schema for GRADUATION
-- 1. ROLES

CREATE TABLE roles (
    role_id     NUMBER(10,0) GENERATED BY DEFAULT AS IDENTITY,
    role_name   VARCHAR2(50 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),

    CONSTRAINT pk_roles
        PRIMARY KEY (role_id),

    CONSTRAINT uk_roles_role_name
        UNIQUE (role_name),

    CONSTRAINT ck_roles_role_name
        CHECK (role_name IN ('admin', 'instructor', 'student'))
);



-- 2. USERS


CREATE TABLE users (
    account_id RAW(16) NOT NULL,
    role_id    NUMBER(10,0) NOT NULL,
    user_type  VARCHAR2(31 CHAR) NOT NULL,
    name       VARCHAR2(250 CHAR) NOT NULL,
    password   VARCHAR2(250 CHAR) NOT NULL,
    email      VARCHAR2(300 CHAR) NOT NULL,

    active     NUMBER(1,0) NOT NULL,

    created_at TIMESTAMP(9),
    updated_at TIMESTAMP(9),

    CONSTRAINT pk_users
        PRIMARY KEY (account_id),

    CONSTRAINT uk_users_email
        UNIQUE (email),

    CONSTRAINT ck_users_active
        CHECK (active IN (0, 1)),

    CONSTRAINT ck_users_user_type
        CHECK (user_type IN ('User', 'INSTRUCTOR', 'STUDENT')),

    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
);



-- 3. STUDENTS


CREATE TABLE students (
                          account_id RAW(16) NOT NULL,
                          phone      VARCHAR2(15 CHAR),

    CONSTRAINT pk_students
        PRIMARY KEY (account_id),

    CONSTRAINT fk_students_user
        FOREIGN KEY (account_id)
        REFERENCES users (account_id)
);


-- 4. INSTRUCTORS

CREATE TABLE instructors (
    account_id        RAW(16) NOT NULL,

    bio                VARCHAR2(500 CHAR),
    experience_years   NUMBER(10,0),

    cv_file_name       VARCHAR2(255 CHAR),
    cv_file_size       NUMBER(10,0),
    cv_file            BLOB,
    cv_uploaded_at     TIMESTAMP(9),

    CONSTRAINT pk_instructors
        PRIMARY KEY (account_id),

    CONSTRAINT fk_instructors_user
        FOREIGN KEY (account_id)
        REFERENCES users (account_id)
);



-- 5. COURSES


CREATE TABLE courses (
    crs_id RAW(16) NOT NULL,
    instructor_id RAW(16) NOT NULL,
    crs_name VARCHAR2(300 CHAR) NOT NULL,
    description   VARCHAR2(1000 CHAR),
    thumbnail_url VARCHAR2(500 CHAR),

    status        VARCHAR2(20 CHAR),

    created_at    TIMESTAMP(9),
    updated_at    TIMESTAMP(9),

    CONSTRAINT pk_courses
        PRIMARY KEY (crs_id),

    CONSTRAINT ck_courses_status
        CHECK (status IN ('draft', 'published', 'archived')),

    CONSTRAINT fk_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES instructors (account_id)
);



-- 6. SESSIONS


CREATE TABLE sessions (
                          session_id      RAW(16) NOT NULL,
                          crs_id          RAW(16) NOT NULL,

                          session_name    VARCHAR2(300 CHAR) NOT NULL,
    description     VARCHAR2(1000 CHAR),
    thumbnail_url   VARCHAR2(500 CHAR),
    video_url       VARCHAR2(500 CHAR),

    duration_minutes NUMBER(10,0) NOT NULL,
    session_order    NUMBER(10,0),

    status          VARCHAR2(20 CHAR),

    created_at      TIMESTAMP(9),
    updated_at      TIMESTAMP(9),

    CONSTRAINT pk_sessions
        PRIMARY KEY (session_id),

    CONSTRAINT ck_sessions_status
        CHECK (status IN ('draft', 'published', 'archived')),

    CONSTRAINT fk_sessions_course
        FOREIGN KEY (crs_id)
        REFERENCES courses (crs_id)
);



-- 7. ENROLLMENT


CREATE TABLE enrollment (
                            account_id      RAW(16) NOT NULL,
                            crs_id          RAW(16) NOT NULL,

                            enrollment_date DATE,

                            status          VARCHAR2(20 CHAR),

    created_at      TIMESTAMP(9),

    CONSTRAINT pk_enrollment
        PRIMARY KEY (account_id, crs_id),

    CONSTRAINT ck_enrollment_status
        CHECK (status IN ('in_progress', 'completed', 'dropped')),

    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (account_id)
        REFERENCES students (account_id),

    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (crs_id)
        REFERENCES courses (crs_id)
);



-- 8. DONE_SESSIONS


CREATE TABLE done_sessions (
                               session_id   RAW(16) NOT NULL,
                               student_id   RAW(16) NOT NULL,

                               is_completed NUMBER(1,0),
                               progress     NUMBER(5,2),

                               completed_at TIMESTAMP(9),
                               last_updated TIMESTAMP(9),

                               CONSTRAINT pk_done_sessions
                                   PRIMARY KEY (session_id, student_id),

                               CONSTRAINT ck_done_sessions_completed
                                   CHECK (is_completed IN (0, 1)),

                               CONSTRAINT fk_done_sessions_session
                                   FOREIGN KEY (session_id)
                                       REFERENCES sessions (session_id),

                               CONSTRAINT fk_done_sessions_student
                                   FOREIGN KEY (student_id)
                                       REFERENCES students (account_id)
);

--Added Indexes for better performance: Data Retrieval

CREATE INDEX idx_users_role_id
    ON users (role_id);


CREATE INDEX idx_courses_instructor_id
    ON courses (instructor_id);


CREATE INDEX idx_courses_status
    ON courses (status);


CREATE INDEX idx_sessions_crs_id
    ON sessions (crs_id);

CREATE INDEX idx_sessions_course_order
    ON sessions (crs_id, session_order);

CREATE INDEX idx_sessions_status
    ON sessions (status);


CREATE INDEX idx_enrollment_crs_id
    ON enrollment (crs_id);

CREATE INDEX idx_done_sessions_student
    ON done_sessions (student_id);

CREATE INDEX idx_done_sessions_student_completed
    ON done_sessions (student_id, is_completed);
CREATE INDEX idx_courses_name
    ON courses (crs_name);
CREATE INDEX idx_students_phone
    ON students (phone);